apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol : TCP
      nodePort: 30000